### PR TITLE
Allow more permissive cell types, Number, Buffer, etc. as long as the object passed in implements a `toString()` method

### LINKED ISSUE #32: Typescript types are too restrictive
In the `serialize` method, anything that's not `null` or `undefined` is going to get passed to the `String` constructor so any value that implements a `toString()` method should be acceptable as a table cell value.

### PR DESCRIPTION
**Pull request by ryantate13**
Closes #32

### CODE REVIEW

**Comment by wooorm** [comment]
Hi!

Hmm, I don’t think that’s a good idea.

It is correct that any value is accepted. But “Accepted” here means: turned into a string.

There are other functions in JavaScript (DOM APIs, Node APIs) that turn anything into a string, but that are still typed by TypeScript so that you have to do that explicitly yourself.

A similar case exists where we don’t need arrays: you can pass anything that has a `length` field. But you probably shouldn’t do that.

Allowing `any` would result in the exact bugs that TS tries to prevent. You might accidentally pass a function, where you meant to call it, and TS wouldn’t catch it.

Types are supposed to help users prevent bugs, and I think the result of this would be opposing that. So, thanks, but no thanks!

**Comment by remcohaszing** [comment]
@wooorm asked my opinion on this. I agree with his previous comment. As can be seen in [this playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAysBOBLAdgcwvKBeKBvAUFEVMAPZxJoBcUAFAJTYB8UAzgiqvgL774A2EYFABuAQ34BXCDQqcMfcVOg5cvJdOxRkk-v3waVUScgAmEAGYoIpgxM04A5I7vKtAFgBMrhyXjSfIwZmPHV7IwB5ACMAKwgAY2AAOnj4CDFgCFodPXpArTUoMVYoACUE0nhTAB52SlQAGjYONCZ81RJyFtQaYKwWAEYAZiGAdiheIA), almost anything is assignable to `Stringer`.

Even the last value would coerce to a pretty string, so effectively the desired type as proposed here would be `any`.

I do think it could be nice to support `number | boolean`, as they are known commonly used values that result in pretty string representations.

**Comment by ryantate13** [comment]
You guys realize what you're opposed to is accurately documenting the nature of the library, correct? Functions have a `toString` method. Users might conceivably want to output a table of their source code. This works fine using this library in untyped JavaScript. What we have instead is an artificial limitation on just the typescript functionality. An untyped representation will print just fine. Typescript users instead wind up having to double stringify everything in the matrix. A needless performance penalty and more complexity to maintain at the call site, especially given the fact that this library does the work anyway.

**Comment by ryantate13** [comment]
That, or type cast and when you know for a fact you can always use `as` safely when passing input to a library, that's a symptom that the types might not be as accurate as they could be. I think that's definitely what we're seeing in this case.

**Comment by remcohaszing** [comment]
Neither the readme nor the jsdoc describes how this library behaves for non-string values. How this should behave is undefined. The intended usage is to pass a matrix of strings.

At runtime values are coerced. An alternative approach could have been to throw. Both approaches could be acceptable to handle invalid usage.

The types signal intended usage: pass a matrix of strings. I don't think it's either right or wrong to loosen these types, it's subjective. In such a case the maintainer is right.

**Comment by ryantate13** [comment]
My PR documents the coercion. I think to throw is a bit silly because the usage is in no way invalid. The language authors intended for objects to be converted to strings this way the same way that `toJSON` controls serialization to that format. To pretend otherwise just imposes an artificial restriction, leaving functionality on the table users could otherwise benefit from.

**Comment by wooorm** [comment]
Docs are restrictions of behavior. Types are docs.

You are supposed to pass strings. That's documented. That's typed.

**Comment by ryantate13** [comment]
I get that. My point is that it isn't reflective of the actual functionality the library provides. If you pass numbers, it works just fine. Same for buffers and whatnot. The documentation as it exists today is inaccurate

**Comment by wooorm** [comment]
Correct, because you shouldn't do that. As remco pointed out earlier, it's undocumented behavior that you shouldn't depend on. Of course, I like this behavior better than throwing, but you still shouldn't depend on it.

Types are supposed to catch bugs. This PR prevents that. If you don't want to follow our recommendations, do your thing, but you are on your own!

**Comment by wooorm** [comment]
There is so much precedence with how TS works. One example:

```
const node = document.body

node.textContent = 1
```

TS will throw. JS thinks its fine. It works in the DOM, but it’s not recommended.

**Comment by ryantate13** [comment]
There's also a ton of precedent for empowering developers with the ability to define how their objects convert to strings. Eventually obtaining a string value seems unavoidable by this library due to the need to calculate cell width. The `Options` format allows for customizing width calculation behavior by passing in a custom `(string) => number` function. The return value of the function itself is string so even some hypothetical alternative intermediate format would eventually have `toString()` called on it. The benefit that it seems you're hesitant to forgo is documentation of the fact that the string constructor gets called on a per-cell basis. To not do so would be a breaking change with little tangible benefit. We could argue that the best way to go about handling string conversion would be better served by passing in a function in the options to maintain consistency with width calculations. That's non-canonical however. As we've seen in your playground example, the string conversion process for objects in JavaScript is well defined and ubiquitous. To go against that pattern would afford users less flexibility, a single function would have to handle all cell conversions instead of objects providing their own implementation as is standard. The point about other APIs that accept numbers not being accurately reflected in their typescript types, while true, would suggest the need to me to have those updated to reflect their actual functionality, not serve as motivation to emulate their shortcomings.

**Comment by wooorm** [comment]
Sounds like you have a problem with typescript. You don't have to use it. Or, you can raise issues with them.

I don't understand your reasoning above.

Perhaps you can share examples where typescript types accept anything that has a valueOf or toString function.

**Comment by ryantate13** [comment]
I'm not sure what I said that gave you the impression I "have a problem with Typescript". Typescript is amazing. What's ironic about your request for examples is that this library, despite your insistence otherwise, is a perfect example of where the `toString` interface makes a lot of sense. I find your comment hostile though, so I'll discontinue our discussion and seek to contribute in the future where interactions with the community focus on the merits of a given argument vs. devolving into personal attacks. I wish you the best of luck with your library in the future.

**Pull request closed without merging**
